Add commenting section to the blog
kaaviya98/JUST___Blog pull request #14
Opened 2022-11-12 14:53 UTC by kaaviya98

2022-11-14 06:22 UTC, bharathwaaj requested changes

2022-11-14 06:22 UTC, bharathwaaj commented on mysite/blog/views.py
> +       return  post.comments.filter(active=True)
Move this into a manager method called active()

`post.comments.active()`

2022-11-14 06:22 UTC, bharathwaaj commented on mysite/blog/templates/blog/post/detail.html
> +  {% for comment in comments %}
This will then become post.comments.active. No need to pass comments.

2022-11-14 06:22 UTC, bharathwaaj commented on mysite/blog/views.py
> +        comment_form = CommentForm()
```
form = CommentForm(data=request.POST or None)
if form.is_valid():
    comment = form.save(commit=False)
    comment.post = post
    comment.save()
    messages.success("Comment added successfully")
    return HttpRedirect("post-detail")
    
return render(request, "blog/post/detail.html", {"post": post, "form": form})
```

Also read https://stackoverflow.com/questions/38240103/why-do-we-need-redirect-after-sending-post-request

2022-11-29 10:12 UTC, waranlogesh requested changes

2022-11-29 10:12 UTC, waranlogesh commented on mysite/blog/templates/blog/post/detail.html
> +    {% endif %}
Move this to the base template. This is common for all.

2022-11-29 10:12 UTC, waranlogesh commented on mysite/blog/views.py
> +    comment_form = CommentForm()
Confusing. The view is doing more than one thing.

Add a separate route to add comment to a post `<int:post_id>/comment/`. This should be function base view that accepts only POST request.

In the view get the post using (get_object_or_404) and get the comment from the request.POST and create the comment for the post

2022-11-29 10:12 UTC, waranlogesh commented on mysite/blog/templates/blog/post/detail.html
> +    <form method="post">
```suggestion
    <form method="post" action="url of <int:post_id>/comment/">

```
Check the bellow comment on handling this in a separate view

2022-11-30 10:05 UTC, waranlogesh approved these changes

2022-11-30 10:14 UTC, merged